server:
  port: 8001
spring:
  application:
    name: app-feign-order
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

##设置Feign客户端超时时间，默认时间是1秒
ribbon:
    #指的是建立连接所用时间，适用于网络状况正常的情况下，两段连接所用的时间
    ReadTimeout: 50000
    #指的是建立连接后从服务器读取到可用资源所用的时间
    ConnectTimeout: 50000

##开起Hystrix断路器
feign:
  hystrix:
    enabled: true

hystrix禁止服务超时时间
hystrix:
  command:
    default:
      exception:
        timeout:
          enabled: false