#服务端口号
server:
  port: 8030
#服务名称
spring:
  application:
    name: pay
#服务注册到eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2